from typing import Protocol

class function_ports(Protocol):



    def create_table(self) -> None:...



    def add_user(self, user_id: str) -> None:...

    def search_user(self, user_id: str):...

    def add_fund(self, user_id, fund) -> None:...



    def add_cards(self, cards:list) -> None:...
    
    def search_card(self, card_id: int, user_id: str):...
    def search_card_last(self, user_id: str):...
    def search_cards(self, user_id:str):...

    def set_card_user(self, new_card_id: int, new_user_id: str, card_id: int, user_id: str) -> None:...
    def delete_card(self, user_id:str, card_id: int) -> None:...


    # def create_band(self, user_id: str) -> None:...

    # def search_band(self, user_id: str):...

    # def delete_band(self, user_id: str, band_id: int) -> None:...

