
working_dict = {
        "SPACE": {'popipa':1.5,
                  'afterglow':1.2,
                  'roselia':1.2,
                  'hello_happy_world':1.2,
                  'pastel_palettes':1.2,
                  "morfonica":1.2,
                  'RAS':1.2,
                  "mygo":1.2,
                  "ave mujica":1.2},
        "CiRCLE": {'popipa':1.2,
                    'afterglow':1.2,
                    'roselia':1.2,
                    'hello_happy_world':1.2,
                    'pastel_palettes':1.2,
                    "morfonica":1.2,
                    'RAS':1.2,
                    "mygo":1.2,
                    "ave mujica":1.2},
        "RiNG": {'popipa':1.2,
                 'afterglow':1.2,
                 'roselia':1.2,
                 'hello_happy_world':1.2,
                 'pastel_palettes':1.2,
                 "morfonica":1.2,
                 'RAS':1.2,
                 "mygo":1.5,
                 "ave mujica":1.5},

        "Yamabuki_Bakery": {'popipa':1.5,
                            'afterglow':1.2,    
                            'roselia':1.2,
                            'hello_happy_world':1.2,
                            'pastel_palettes':1.2,
                            "morfonica":1.2,
                            'RAS':1.2,
                            "mygo":1.2,
                            "ave mujica":1.2},
        "wutagawa_laamen": {'popipa':1.2,
                            'afterglow':1.5,
                            'roselia':1.5,
                            'hello_happy_world':1.2,
                            'pastel_palettes':1.2,
                            "morfonica":1.2,
                            'RAS':1.2,
                            "mygo":1.2,
                            "ave mujica":1.2},
        "rokka_onsenryokan": {'popipa':1.2,
                              'afterglow':1.2,
                              'roselia':1.2,
                              'hello_happy_world':1.2,
                              'pastel_palettes':1.2,
                              "morfonica":1.2,
                              'RAS':1.5,
                              "mygo":1.2,
                              "ave mujica":1.2},
        "Tsurumaki_amusement_park": {'popipa':1.2,
                                     'afterglow':1.2,
                                     'roselia':1.2,
                                     'hello_happy_world':1.5,
                                     'pastel_palettes':1.2,
                                     "morfonica":1.2,
                                     'RAS':1.2,
                                     "mygo":1.2,
                                     "ave mujica":1.2},


        "Yoshinoya": {"toge":1.5},
        'STARRY': {"kessoku band":1.5},

    }